import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserTaskContextProvider } from "@/context/UserTaskContext";

import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // choose weights you need
});

export const metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased bg-slate-950 text-slate-100`}
      >
        <UserTaskContextProvider>
          <Header />
          <Toaster />
          <div className="min-h-screen flex relative">
            <Sidebar />
            {children}
          </div>
        </UserTaskContextProvider>
      </body>
    </html>
  );
}
